kind: pipeline
name: PA
steps:
- name: Build
  image: apon77/aosp:latest
  environment:
    DRONE_USER_CREATE: username:massterpiece,admin:true
  commands:
  - cd /drone/src
  - sudo bash -E sync.sh
  - sudo bash -E build.sh
